
package Ejecucion;

import Administrador.Ayuda;
import Administrador.Disponible;
import Panel_Ingresar_y_Salir_Vehiculo.Ingresar_Vehiculo;
import Panel_Ingresar_y_Salir_Vehiculo.Salir_Vehiculo;
import  Paneles_Usuario.Agrega_Usuario;
import java.awt.Desktop;
import java.awt.Font;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRPrintElement;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author TaGCode
 */
public final class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    
    Ingresar_Vehiculo obj ;
    Salir_Vehiculo salir ;
    Agrega_Usuario agregaruser ; 
    Login jaja ;
    Disponible Caja ;
    Administrador.Factura Factura ;
    Connection con;
    SimpleDateFormat Español = new SimpleDateFormat("dd/MMMM/YYYY ",new Locale("es"));
    Date Fecha = new Date();
    public Inicio() throws ClassNotFoundException, SQLException  {
        System.gc();
        con = ConectarBD.ConexcionBD.Conectar();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("TaGCode Parcking Lot");
        mENUBOTON.setText("User:");
        mENUBOTON.setFont(new Font("Dialog", Font.BOLD, 14));
        MenuLogin.setFont(new Font("Dialog", Font.BOLD, 14));
    }
    
    /**
     * ESTE METODO ESTA HECHO PARA QUE 
     * SALGA LA VENTANA DE ERROR 
     * YA QUE ESTA REPIDIENDOSE MUCHAS VECES 
     */
    void Error(){
        getToolkit().beep();
        JOptionPane.showMessageDialog(null, "VENTANA EN EJECUCION", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMenuReporte = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        MenuDisponible = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuMantenimiento = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        JmenuFactura = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        mENUBOTON = new javax.swing.JMenu();
        MenuLogin = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/Icon/Carro.png")).getImage()
        );
        setMinimumSize(new java.awt.Dimension(1100, 700));

        jPanel2.setBackground(new java.awt.Color(60, 141, 168));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(60, 141, 168));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1057, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1057;
        gridBagConstraints.ipady = 566;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 6, 6);
        jPanel2.add(jPanel1, gridBagConstraints);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Startupfolder_5942.png"))); // NOI18N
        jMenu1.setText("Menu");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        JMenuReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/file_type_pdf_icon_130274.png"))); // NOI18N
        JMenuReporte.setText("Reporte PDF");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/file_type_pdf_icon_130274.png"))); // NOI18N
        jMenuItem6.setText("Entrada Vehiculo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        JMenuReporte.add(jMenuItem6);

        jMenu1.add(JMenuReporte);

        MenuDisponible.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        MenuDisponible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Disponible.png"))); // NOI18N
        MenuDisponible.setText("Disponible");
        MenuDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDisponibleActionPerformed(evt);
            }
        });
        jMenu1.add(MenuDisponible);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Recuso 48px.png"))); // NOI18N
        jMenu2.setText("Recursos");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Ingresar Vehiculo.png"))); // NOI18N
        jMenuItem3.setText("Ingresar Vehiculo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/vcsremoved_103741_1.png"))); // NOI18N
        jMenuItem4.setText("Eliminar Vehiculo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        MenuMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/menu_editconfig_men_9554.png"))); // NOI18N
        MenuMantenimiento.setText("Mantenimiento");
        MenuMantenimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Add.png"))); // NOI18N
        jMenuItem5.setText("Usuario");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        MenuMantenimiento.add(jMenuItem5);

        jMenuBar1.add(MenuMantenimiento);

        JmenuFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Factura.png"))); // NOI18N
        JmenuFactura.setText("Factura");
        JmenuFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JmenuFacturaMouseClicked(evt);
            }
        });
        jMenuBar1.add(JmenuFactura);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/browser_internet_network_6248.png"))); // NOI18N
        jMenu5.setText("Web Site");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Google_Chrome_icon-icons.com_75711.png"))); // NOI18N
        jMenuItem2.setText("Google");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/3721679-youtube_108064.png"))); // NOI18N
        jMenuItem7.setText("YouTube");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cerrar Sesion.png"))); // NOI18N
        jMenu6.setText("Cerrar Sesion");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Help_43559.png"))); // NOI18N
        jMenu4.setText("Ayuda");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        mENUBOTON.setText("jMenu9");
        jMenuBar1.add(mENUBOTON);

        MenuLogin.setText("jMenu9");
        jMenuBar1.add(MenuLogin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1069, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
//        Usuario.setVisible(false);
        obj = new Ingresar_Vehiculo();
        if (jPanel1.getComponentCount() > 0) {
            Error();

        }else{
            jPanel1.add(obj);
            jPanel1.revalidate();
            jPanel1.repaint();
            obj.setSize(1060, 570);
            obj.setVisible(true);
            
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://www.google.com/"));
        } catch (URISyntaxException | IOException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex , "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://www.youtube.com/"));
        } catch (URISyntaxException | IOException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex , "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed
    
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        salir = new Salir_Vehiculo();
        if (jPanel1.getComponentCount() > 0) {
            Error();
        }else{
            jPanel1.add(salir);
            jPanel1.revalidate();
            jPanel1.repaint();
            salir.setSize(1060, 570);
            salir.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        agregaruser= new Agrega_Usuario();
        if (jPanel1.getComponentCount() > 0) {
            Error();
        }else{
            jPanel1.add(agregaruser);
            jPanel1.revalidate();
            jPanel1.repaint();
            agregaruser.setSize(1060, 570);
            agregaruser.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    
    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        
        
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        this.dispose();
        jaja = new Login();
        jaja.setVisible(true);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void MenuDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDisponibleActionPerformed
        Caja = new Disponible();
        if (jPanel1.getComponentCount() > 0) {
            Error();
        }else{
            jPanel1.add(Caja);
            jPanel1.revalidate();
            jPanel1.repaint();
            Caja.setSize(1056, 573);
            Caja.setVisible(true);
        }
        
    }//GEN-LAST:event_MenuDisponibleActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        Ayuda ayuda = new Ayuda(null, true);
        ayuda.setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void JmenuFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JmenuFacturaMouseClicked
        Factura = new Administrador.Factura();
        if (jPanel1.getComponentCount() > 0) {
            Error();
        }else{
            jPanel1.add(Factura);
            jPanel1.revalidate();
            jPanel1.repaint();
            Factura.setSize(1060, 570);
            Factura.setVisible(true);
        }
    }//GEN-LAST:event_JmenuFacturaMouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        String aux = Español.format(Fecha);
        try {
            Map <String , String> parametro = new HashMap<String, String>();
            parametro.put("fecha",aux );
            JasperReport Reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/reportes/Entrada_vehiculo.jasper"));
            JasperPrint Imprimir = JasperFillManager.fillReport(Reporte,parametro, con);
            JasperViewer ver = new JasperViewer(Imprimir , false);
            ver.setTitle("Entrada de Vehiculos Del " + aux);
            ver.setIconImage(new ImageIcon(getClass().getResource("/Icon/Carro.png")).getImage());
            ver.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex , "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Inicio().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Error " + ex , "Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenu JMenuReporte;
    private javax.swing.JMenu JmenuFactura;
    private javax.swing.JMenuItem MenuDisponible;
    public static javax.swing.JMenu MenuLogin;
    public static javax.swing.JMenu MenuMantenimiento;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu mENUBOTON;
    // End of variables declaration//GEN-END:variables
}
