/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejecucion;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Steven
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    Inicio iniciar ;
    public Login() {
        try {
            System.gc();
            initComponents();
            iniciar = new Inicio();
            //this.setExtendedState(MAXIMIZED_BOTH);
            this.setLocationRelativeTo(this);
            this.setTitle("Login TaGCode Parcking Lot");
            Color obj = new Color(255 , 255, 255,100  );
            Inicio.setBackground(obj);
            setIconImage(new ImageIcon(getClass().getResource("/Icon/Carro.png")).getImage());
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex , "Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        Inicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtusuarip = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jpasscontrasenia = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        botonEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(60, 141, 168));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        Inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Carro.png"))); // NOI18N
        Inicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 140, 150));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Usuario:");
        Inicio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/customer_person_people_man_user_client_1629.png"))); // NOI18N
        Inicio.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 40));

        jtxtusuarip.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtusuarip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtusuaripKeyTyped(evt);
            }
        });
        Inicio.add(jtxtusuarip, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 210, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Contraseña:");
        Inicio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jpasscontrasenia.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jpasscontrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpasscontraseniaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpasscontraseniaKeyTyped(evt);
            }
        });
        Inicio.add(jpasscontrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 210, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/security-protection-protect-key-password-login_108554.png"))); // NOI18N
        Inicio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 40));

        botonEntrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonEntrar.setText("Entrar");
        botonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntrarActionPerformed(evt);
            }
        });
        Inicio.add(botonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 160, 60));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        jPanel2.add(Inicio, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void botonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntrarActionPerformed
        if (jtxtusuarip.getText().equals("Admin") && jpasscontrasenia.getText().equals("1234")) {
            Ejecucion.Inicio.MenuMantenimiento.setEnabled(true);
            Ejecucion.Inicio.JMenuReporte.setEnabled(true);
            Ejecucion.Inicio.MenuLogin.setText("ADMINISTRADOR");
            iniciar.setVisible(true);
            this.setVisible(false);
        }else if (jtxtusuarip.getText().equals("Empleado") && jpasscontrasenia.getText().equals("1234")){
            Ejecucion.Inicio.MenuMantenimiento.setEnabled(false);
            Ejecucion.Inicio.JMenuReporte.setEnabled(false);
            Ejecucion.Inicio.MenuLogin.setText("EMPLEADO");
            iniciar.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            jtxtusuarip.requestFocus();
            JOptionPane.showMessageDialog(null, "Error ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEntrarActionPerformed

    private void jpasscontraseniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpasscontraseniaKeyTyped
        if(jtxtusuarip.getText().length() > (10 -1)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error",JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if ((caracteres < 48 || caracteres > 57) && (caracteres != 8) && (caracteres != 10)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jpasscontraseniaKeyTyped

    private void jpasscontraseniaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpasscontraseniaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            botonEntrar.doClick();
        }
    }//GEN-LAST:event_jpasscontraseniaKeyPressed

    private void jtxtusuaripKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtusuaripKeyTyped
        if(jtxtusuarip.getText().length() > (10 -1)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error",JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if((caracteres < 65 || caracteres > 90) && (caracteres < 97 || caracteres >122 ) && (caracteres != 8) && (caracteres != 10 ) ){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtusuaripKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Inicio;
    private javax.swing.JButton botonEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jpasscontrasenia;
    private javax.swing.JTextField jtxtusuarip;
    // End of variables declaration//GEN-END:variables
}
