/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrador;

import Ejecucion.Inicio;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Steven
 */
public class Factura extends javax.swing.JPanel {

    /**
     * Creates new form Factura
     */
    SimpleDateFormat Español = new SimpleDateFormat("dd/MMMM/YYYY ",new Locale("es"));
    Date Fecha = new Date();
    Connection con ;
    public Factura() {
        initComponents();
        try {
            con = ConectarBD.ConexcionBD.Conectar();
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error "+ex ," Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    void limpiar(){
        jtxtcedula.setText("");
        jtxtNombre.setText("");
        jtxtpellido.setText("");
        jtxtTelefono.setText("");
        jtxtCorreo.setText("");
        jtxtTotalPago.setText("");
        jTextArea1.setText("");
        jtxtDireccion.setText("");
        jtxtBuscar.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtBuscar = new javax.swing.JTextField();
        jbotonBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbotonGenerar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jtxtcedula = new javax.swing.JTextField();
        jtxtpellido = new javax.swing.JTextField();
        jtxtTelefono = new javax.swing.JTextField();
        jtxtDireccion = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jtxtCorreo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtTotalPago = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FACTURA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 36))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel1.setText("Cedula:");

        jtxtBuscar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtBuscarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBuscarKeyTyped(evt);
            }
        });

        jbotonBuscar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Buscar.png"))); // NOI18N
        jbotonBuscar.setText("Buscar");
        jbotonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbotonBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbotonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbotonBuscar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbotonGenerar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbotonGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Add_40971.png"))); // NOI18N
        jbotonGenerar.setText("Generar ");
        jbotonGenerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbotonGenerarMouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/action_exit_close_remove_13915.png"))); // NOI18N
        jButton3.setText("Salir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbotonGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbotonGenerar)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Cedula:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Apellido:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Telefono:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Direccion:");

        jtxtNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyTyped(evt);
            }
        });

        jtxtcedula.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtcedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcedulaKeyTyped(evt);
            }
        });

        jtxtpellido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtpellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtpellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtpellidoKeyTyped(evt);
            }
        });

        jtxtTelefono.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTelefonoKeyTyped(evt);
            }
        });

        jtxtDireccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDireccionKeyTyped(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESCRIPCION", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Total:");

        jtxtCorreo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtCorreoKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Correo:");

        jtxtTotalPago.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jtxtTotalPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTotalPagoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                    .addComponent(jtxtpellido)
                    .addComponent(jtxtTelefono)
                    .addComponent(jtxtDireccion)
                    .addComponent(jtxtCorreo))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtTotalPago, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxtpellido, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jtxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtxtTotalPago, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        int aux = JOptionPane.showConfirmDialog(null, "Esta Seguro Salir ", "Salir", JOptionPane.ERROR_MESSAGE);
        if (aux == JOptionPane.YES_OPTION) {
            getToolkit().beep();
            this.setVisible(false);
            Inicio.jPanel1.removeAll();
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jbotonGenerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbotonGenerarMouseClicked

        if (jtxtcedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Cedula Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Nombre Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtpellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Apellido Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtTelefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Telefono Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtDireccion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Direccion Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtCorreo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Correo Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else if (jTextArea1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Descripcion Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtTotalPago.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Total a Pagar Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                String aux = Español.format(Fecha);
                float pago = Float.parseFloat(jtxtTotalPago.getText().trim());
                String SQL = "INSERT INTO factura (fecha,ruc,nombre_cliente,apellido_cliente,telefono_cliente,correo_cliente,pago,descripcion,direccion) VALUES (?,?,?,?,?,?,?,?,?) ";
                PreparedStatement preparar = con.prepareStatement(SQL);
                preparar.setString(1, aux.toUpperCase());
                preparar.setString(2, jtxtcedula.getText().trim().toUpperCase());
                preparar.setString(3, jtxtNombre.getText().toUpperCase());
                preparar.setString(4, jtxtpellido.getText().toUpperCase());
                preparar.setString(5, jtxtTelefono.getText().trim().toUpperCase());
                preparar.setString(6, jtxtCorreo.getText().trim());
                preparar.setFloat(7, pago);
                preparar.setString(8, jTextArea1.getText().toUpperCase());
                preparar.setString(9, jtxtDireccion.getText().toUpperCase());
                preparar.executeUpdate();
                factura(jtxtcedula.getText().trim());
                limpiar();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error " + ex, "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_jbotonGenerarMouseClicked

    private void jbotonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbotonBuscarMouseClicked
        if (jtxtBuscar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese Datos para buscar", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
        try {
            String SQL = "SELECT * FROM factura WHERE ruc =\'"+jtxtBuscar.getText().trim()+"\'";
            PreparedStatement preparar = con.prepareStatement(SQL);
            ResultSet resultado = preparar.executeQuery();
            eliminar();
            limpiar();
            while (resultado.next()) {   
                jtxtcedula.setText(resultado.getString("ruc"));
                jtxtNombre.setText(resultado.getString("nombre_cliente"));
                jtxtpellido.setText(resultado.getString("apellido_cliente"));
                jtxtTelefono.setText(resultado.getString("telefono_cliente"));
                jtxtCorreo.setText(resultado.getString("correo_cliente"));
                jtxtDireccion.setText(resultado.getString("direccion"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex, "Error", JOptionPane.INFORMATION_MESSAGE);        
        }
    }//GEN-LAST:event_jbotonBuscarMouseClicked

    private void jtxtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarKeyTyped
        if (jtxtBuscar.getText().length() > (10 - 1)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error", JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if ((caracteres < 48 || caracteres > 57) && (caracteres != 8) && (caracteres != 10)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtBuscarKeyTyped

    private void jtxtcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcedulaKeyTyped
        if (jtxtcedula.getText().length() > (10 - 1)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error", JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if ((caracteres < 48 || caracteres > 57) && (caracteres != 8) && (caracteres != 10)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtcedulaKeyTyped

    private void jtxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyTyped
        if (jtxtNombre.getText().length() > (40 - 1)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error", JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if((caracteres < 65 || caracteres > 90) && (caracteres < 97 || caracteres >122 ) && (caracteres != 8) && (caracteres != 10 ) && (caracteres != 32 ) ){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtNombreKeyTyped

    private void jtxtpellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpellidoKeyTyped
        if (jtxtpellido.getText().length() > (40 - 1)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error", JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if((caracteres < 65 || caracteres > 90) && (caracteres < 97 || caracteres >122 ) && (caracteres != 8) && (caracteres != 10 ) && (caracteres != 32 ) ){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtpellidoKeyTyped

    private void jtxtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTelefonoKeyTyped
        if (jtxtTelefono.getText().length() > (10 - 1)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error", JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if ((caracteres < 48 || caracteres > 57) && (caracteres != 8) && (caracteres != 10)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtTelefonoKeyTyped

    private void jtxtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDireccionKeyTyped
        if(jtxtDireccion.getText().length() > (100 -1)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error",JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if((caracteres < 65 || caracteres > 90) && (caracteres < 97 || caracteres >122 ) && (caracteres <48 || caracteres >57) 
                && (caracteres != 8) && (caracteres != 10 ) ){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtDireccionKeyTyped

    private void jtxtTotalPagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTotalPagoKeyTyped
        if (jtxtTotalPago.getText().length() > (5)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error", JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if ((caracteres < 48 || caracteres > 57) && (caracteres != 8) && (caracteres != 10) && (caracteres != 44) && (caracteres != 46) ) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtTotalPagoKeyTyped

    private void jtxtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarKeyPressed
        if (evt.isControlDown() || evt.isShiftDown() || evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtBuscarKeyPressed

    private void jtxtcedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcedulaKeyPressed
        if (evt.isControlDown() || evt.isShiftDown() || evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtcedulaKeyPressed

    private void jtxtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyPressed
        if (evt.isControlDown() || evt.isShiftDown() || evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtNombreKeyPressed

    private void jtxtpellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpellidoKeyPressed
        if (evt.isControlDown() || evt.isShiftDown() || evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtpellidoKeyPressed

    private void jtxtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTelefonoKeyPressed
        if (evt.isControlDown() || evt.isShiftDown() || evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtTelefonoKeyPressed

    private void jtxtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDireccionKeyPressed
        if (evt.isControlDown() || evt.isShiftDown() || evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtDireccionKeyPressed

    private void jtxtCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCorreoKeyPressed
        if (evt.isControlDown() || evt.isShiftDown() || evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtCorreoKeyPressed
    /**
     * <p> Este metodo esta creado para la facturacion 
     * lo que hace es que espera que el elemento que manda a buscar el boton  que lo encuentre 
     * y luego lo elimine para que no se genere dos factura con el mismo ruco cedula </p>
     */
    void eliminar(){
        
        try {
            String SQL = "DELETE FROM factura WHERE ruc =\'"+jtxtBuscar.getText().trim()+"\'";
            PreparedStatement preparar =con.prepareStatement(SQL);
            preparar.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex, "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void factura(String aux){
        try {
            Map <String , String> parametro = new HashMap<String, String>();
            parametro.put("cedula", aux);
            JasperReport Reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/reportes/Factura.jasper"));
            JasperPrint Imprimir = JasperFillManager.fillReport(Reporte,parametro, con);
            JasperViewer ver = new JasperViewer(Imprimir, false);
            ver.setTitle("Factura");
            ver.setIconImage(new ImageIcon(getClass().getResource("/Icon/Carro.png")).getImage());
            ver.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbotonBuscar;
    private javax.swing.JButton jbotonGenerar;
    private javax.swing.JTextField jtxtBuscar;
    private javax.swing.JTextField jtxtCorreo;
    private javax.swing.JTextField jtxtDireccion;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtTelefono;
    private javax.swing.JTextField jtxtTotalPago;
    private javax.swing.JTextField jtxtcedula;
    private javax.swing.JTextField jtxtpellido;
    // End of variables declaration//GEN-END:variables
}
