/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles_Usuario;

import Clases.Carro;
import Clases.Empleado;
import Clases.Moto;
import Ejecucion.Inicio;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tabla.ModeloTabla;

/**
 *
 * @author TaGCode
 */
public class Agrega_Usuario extends javax.swing.JPanel implements ConectarBD.Metodos{

    /**
     * Creates new form NewJPanel
     */
    ModeloTabla ColorFila = new ModeloTabla();
    SimpleDateFormat Español = new SimpleDateFormat("dd/MMMM/YYYY ",new Locale("es"));
    Date Fecha = new Date();
    public Agrega_Usuario() {
        System.gc();
        initComponents();
        jTable1.setDefaultRenderer(Object.class, ColorFila);
        jlabelFecha.setText(Español.format(Fecha));
        Font tamanio = new Font("Dialog",Font.BOLD,14);
        jTable1.getTableHeader().setFont(tamanio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtBuscar = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtxtCedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtTelefono = new javax.swing.JTextField();
        jtxtApellido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jtxtCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtSueldo = new javax.swing.JTextField();
        jlabelFecha = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AGREGAR Y ELIMINAR USUARIO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 36))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel1.setText("Usuario:");

        jtxtBuscar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtBuscarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBuscarKeyTyped(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Buscar.png"))); // NOI18N
        jButton5.setText("Buscar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Add_40971.png"))); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/checklist_25365.png"))); // NOI18N
        jButton2.setText("Listar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sign-delete-icon_34364.png"))); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Modificar.png"))); // NOI18N
        jButton4.setText("Limpiar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/action_exit_close_remove_13915.png"))); // NOI18N
        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Nombre:");

        jtxtCedula.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtCedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCedulaKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Apellido:");

        jtxtNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Fecha Entrada:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Rol:");

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMINISTRADOR", "EMPLEADOR" }));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Cedula:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Telefono:");

        jtxtTelefono.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTelefonoKeyTyped(evt);
            }
        });

        jtxtApellido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtApellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtApellidoKeyTyped(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Fecha Entrada", "Roll", "Telefono", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.setFocusable(false);

        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Correo:");

        jtxtCorreo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Sueldo:");

        jtxtSueldo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtSueldoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtSueldoKeyTyped(evt);
            }
        });

        jlabelFecha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox1, 0, 256, Short.MAX_VALUE)
                                            .addComponent(jtxtCedula)
                                            .addComponent(jtxtNombre))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel7))
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(jtxtCorreo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                    .addComponent(jtxtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtSueldo))
                                    .addComponent(jlabelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(52, 52, 52)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6))
                            .addComponent(jlabelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jtxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jtxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtSueldo))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    void Limpiar (){
        jtxtBuscar.setText("");
        jtxtCedula.setText("");
        jtxtApellido.setText("");
        jtxtNombre.setText("");
        jtxtSueldo.setText("");
        jtxtCorreo.setText("");
        jComboBox1.setSelectedIndex(0);
        jtxtTelefono.setText("");
    }
    
//     Listar listar = new Listar();
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        listar();
        Limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       int aux = JOptionPane.showConfirmDialog(null, "Esta Seguro Salir", "Salir", JOptionPane.ERROR_MESSAGE);
        if (aux == JOptionPane.YES_OPTION) {
            getToolkit().beep();
            this.setVisible(false);
            Inicio.jPanel1.removeAll();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (jtxtCedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Cedula Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Nombre Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtApellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Apellido Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtCorreo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo correo Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtTelefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo telefono Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtSueldo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Sueldo Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Double aux = Double.parseDouble(jtxtSueldo.getText().trim());
            Empleado empleado = new Empleado(aux, jtxtCedula.getText().trim(), jtxtNombre.getText().toUpperCase(),
                    jtxtApellido.getText().toUpperCase());
            empleado.setTelefono(jtxtTelefono.getText().trim());
            Insertar(empleado);
            Limpiar();
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if (jtxtBuscar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese la Cedula para Eliminar", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Remover();
            Limpiar();
        }
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        if (jtxtBuscar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese datos para Buscar ", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Buscar();
            Limpiar();
        }
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        Limpiar();
        DefaultTableModel Tabla = (DefaultTableModel) jTable1.getModel();
        Tabla.getDataVector().clear();
        jTable1.updateUI();
        jTable1.setModel(Tabla);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jtxtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarKeyTyped
        if (jtxtBuscar.getText().length() > (10 - 1)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error", JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if ((caracteres < 48 || caracteres > 57) && (caracteres != 8) && (caracteres != 10)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtBuscarKeyTyped

    private void jtxtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCedulaKeyTyped
        if (jtxtCedula.getText().length() > (10 - 1)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error", JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if ((caracteres < 48 || caracteres > 57) && (caracteres != 8) && (caracteres != 10)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtCedulaKeyTyped

    private void jtxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyTyped
        if (jtxtNombre.getText().length() > (40 - 1)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error", JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if((caracteres < 65 || caracteres > 90) && (caracteres < 97 || caracteres >122 ) && (caracteres != 8) && (caracteres != 10 ) && (caracteres != 32 ) ){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtNombreKeyTyped

    private void jtxtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtApellidoKeyTyped
        if (jtxtApellido.getText().length() > (40 - 1)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error", JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if((caracteres < 65 || caracteres > 90) && (caracteres < 97 || caracteres >122 ) && (caracteres != 8) && (caracteres != 10 ) && (caracteres != 32 ) ){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtApellidoKeyTyped

    private void jtxtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTelefonoKeyTyped
        if (jtxtTelefono.getText().length() > (10 - 1)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error", JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if ((caracteres < 48 || caracteres > 57) && (caracteres != 8) && (caracteres != 10)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtTelefonoKeyTyped

    private void jtxtSueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSueldoKeyTyped
        if (jtxtSueldo.getText().length() > (5)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error", JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if ((caracteres < 48 || caracteres > 57) && (caracteres != 8) && (caracteres != 10) && (caracteres != 44) && (caracteres != 46) ) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtSueldoKeyTyped

    private void jtxtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarKeyPressed
        if (evt.isControlDown() || evt.isShiftDown() || evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtBuscarKeyPressed

    private void jtxtCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCedulaKeyPressed
        if (evt.isControlDown() || evt.isShiftDown() || evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtCedulaKeyPressed

    private void jtxtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyPressed
        if (evt.isControlDown() || evt.isShiftDown() || evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtNombreKeyPressed

    private void jtxtApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtApellidoKeyPressed
        if (evt.isControlDown() || evt.isShiftDown() || evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtApellidoKeyPressed

    private void jtxtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTelefonoKeyPressed
        if (evt.isControlDown() || evt.isShiftDown() || evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtTelefonoKeyPressed

    private void jtxtSueldoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSueldoKeyPressed
        if (evt.isControlDown() || evt.isShiftDown() || evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtSueldoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlabelFecha;
    private javax.swing.JTextField jtxtApellido;
    private javax.swing.JTextField jtxtBuscar;
    private javax.swing.JTextField jtxtCedula;
    private javax.swing.JTextField jtxtCorreo;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtSueldo;
    private javax.swing.JTextField jtxtTelefono;
    // End of variables declaration//GEN-END:variables

    public void Insertar(Empleado empleado)  {
        
        try {
            Connection con = ConectarBD.ConexcionBD.Conectar();
            String SQL = "INSERT INTO persona (cedula,nombre,apellido,telefono,tipo_persona,fecha_entrada,correo) VALUES (?,?,?,?,?,?,?)";

            if (jComboBox1.getSelectedIndex() == 0) {
                agregar(SQL, con, empleado);

            } else {
                agregar(SQL, con, empleado);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex , "Error",JOptionPane.ERROR_MESSAGE);
        }
        
        
    }
    
    public void agregar(String SQL , Connection con , Empleado empleado) {
        
        try {
            PreparedStatement preparar = con.prepareStatement(SQL);
            preparar.setString(1, empleado.getCedula().toUpperCase().trim());
            preparar.setString(2, empleado.getNombre().toUpperCase());
            preparar.setString(3, empleado.getApellido().toUpperCase());
            preparar.setString(4, empleado.getTelefono().toUpperCase());
            preparar.setString(5, jComboBox1.getSelectedItem().toString().toUpperCase());
            preparar.setString(6, jlabelFecha.getText().trim().toUpperCase());
            preparar.setString(7, jtxtCorreo.getText().toUpperCase());
            preparar.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos Guardados" , "Guardado" ,JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex , "Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    @Override
    public void Remover() {
       
        try {
            Connection con = ConectarBD.ConexcionBD.Conectar();
            String Sql = "DELETE  FROM persona WHERE cedula =\'"+jtxtBuscar.getText().trim()+"\'";
            PreparedStatement preparar = con.prepareStatement(Sql);
            preparar.executeUpdate();
            JOptionPane.showMessageDialog(null, "Eliminado", "Eliminar",JOptionPane.INFORMATION_MESSAGE);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex , "Error",JOptionPane.ERROR_MESSAGE);
        }
            
    }

    @Override
    public void listar() {
        try {
            Connection con = ConectarBD.ConexcionBD.Conectar();
            String SQL = "SELECT * FROM persona";
            PreparedStatement preparar = con.prepareStatement(SQL);
            ResultSet Resultado = preparar.executeQuery();
            DefaultTableModel Tabla = (DefaultTableModel) jTable1.getModel();
            Tabla.getDataVector().clear();
            jTable1.updateUI();
            while (Resultado.next()) {
                Object[] Datos = new Object[7];
                Datos[0] = Resultado.getString("cedula");
                Datos[1] = Resultado.getString("nombre");
                Datos[2] = Resultado.getString("apellido");
                Datos[3] = Resultado.getString("fecha_entrada");
                Datos[4] = Resultado.getString("tipo_persona");
                Datos[5] = Resultado.getString("telefono");
                Datos[6] = Resultado.getString("correo");
                Tabla.addRow(Datos);
            }
            jTable1.setModel(Tabla);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex, "Error", JOptionPane.ERROR_MESSAGE);

        }
    }

    @Override
    public void Buscar() {
        
        try {
            Connection con = ConectarBD.ConexcionBD.Conectar();
            String SQL = "SELECT * FROM persona WHERE cedula = \'"+jtxtBuscar.getText().trim()+"\'";
            PreparedStatement preparar = con.prepareStatement(SQL);
            ResultSet resultado = preparar.executeQuery();
            DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
            tabla.getDataVector().clear();
            jTable1.updateUI();
            while (resultado.next()) {
                Object[] Datos = new Object[7];
                Datos[0] = resultado.getString("cedula");
                Datos[1] = resultado.getString("nombre");
                Datos[2] = resultado.getString("apellido");
                Datos[3] = resultado.getString("fecha_entrada");
                Datos[4] = resultado.getString("tipo_persona");
                Datos[5] = resultado.getString("telefono");
                Datos[6] = resultado.getString("correo");
                tabla.addRow(Datos);
            }
            jTable1.setModel(tabla);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
            
    }
    
    @Override
    public void Insertar(Carro car, Moto mot) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
