/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel_Ingresar_y_Salir_Vehiculo;

import Clases.Carro;
import Clases.Moto;
import Ejecucion.Inicio;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import tabla.ModeloTabla;

/**
 *
 * @author TaGCode
 */
public class Ingresar_Vehiculo extends javax.swing.JPanel implements ConectarBD.Metodos{

    /**
     * Creates new form Ingresar_Vehiculo
     */
//    DefaultTableModel Tabla;
    SimpleDateFormat Español = new SimpleDateFormat("dd/MM/YYYY    HH:mm:ss",new Locale("es"));
    Date Fecha = new Date();
    ModeloTabla ColorFila = new ModeloTabla();
    SpinnerNumberModel Numero ;
    Carro carro ;
    public Ingresar_Vehiculo() {
        System.gc();
        initComponents();
        jlabelfecha.setText(Español.format(Fecha));
        Numero = new SpinnerNumberModel();
        Numero.setMaximum(10);
        Numero.setMinimum(4);
        Numero.setValue(4);
        jTable1.setDefaultRenderer(Object.class, ColorFila);
        Font tamanio = new Font("Dialog",Font.BOLD,14);
        jTable1.getTableHeader().setFont(tamanio);
    }

    void Limpiar(){
        jtctplaca.setText("");
        jtxtBuscarvehiculo.setText("");
        jtxtpropietario.setText("");
        jtxtareadescripcion.setText("");
        jtxtmarca.setText("");
        jtxtModelo.setText("");
        jtxtareadescripcion.setText("");
        jtxtareadescripcion.setEditable(true);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonAgregar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtBuscarvehiculo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jlabelfecha = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxtareadescripcion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jtxtModelo = new javax.swing.JTextField();
        jtxtpropietario = new javax.swing.JTextField();
        jtctplaca = new javax.swing.JTextField();
        jtxtmarca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcombotipovehiculo = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENTRADA  VEHICULO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 36))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1063, 573));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BotonAgregar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Add_40971.png"))); // NOI18N
        BotonAgregar.setText("Agregar");
        BotonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarMouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/checklist_25365.png"))); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/printer_6029.png"))); // NOI18N
        jButton6.setText("Tickets");

        BotonSalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/action_exit_close_remove_13915.png"))); // NOI18N
        BotonSalir.setText("Salir");
        BotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalirMouseClicked(evt);
            }
        });
        BotonSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BotonSalirKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BotonSalirKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BotonSalirKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(BotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(46, 46, 46)
                .addComponent(BotonSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex , int colIndex){
                return false;
            }
        };
        jTable1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " ID ", "PLACA", "MODELO", "PROPIETARIO", "TIPO VEHICULO", "HORA ENTRADA", "FECHA ENTRADA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.setFocusable(false);

        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Buscar.png"))); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel1.setText("Vehiculo:");

        jtxtBuscarvehiculo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtxtBuscarvehiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtBuscarvehiculoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBuscarvehiculoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtBuscarvehiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtBuscarvehiculo))))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Propietario:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Marca:");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Fecha Entrada:");

        jlabelfecha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Descripcion:");

        jtxtareadescripcion.setColumns(20);
        jtxtareadescripcion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtareadescripcion.setLineWrap(true);
        jtxtareadescripcion.setRows(5);
        jtxtareadescripcion.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jtxtareadescripcion);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Modelo:");

        jtxtModelo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtModeloKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtModeloKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 283, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlabelfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtModelo)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jlabelfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtxtpropietario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtpropietario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtpropietarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtpropietarioKeyTyped(evt);
            }
        });

        jtctplaca.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtctplaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtctplacaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtctplacaKeyTyped(evt);
            }
        });

        jtxtmarca.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtmarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtmarcaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtmarcaKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Placa:");

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tipo Vehiculo");

        jcombotipovehiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CARRO", "MOTOCICLETA" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcombotipovehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcombotipovehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtmarca)
                            .addComponent(jtxtpropietario)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtctplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 96, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtctplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtpropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseClicked
        int aux = JOptionPane.showConfirmDialog(null, "Esta Seguro Salir ", "Salir", JOptionPane.ERROR_MESSAGE);
        if (aux == JOptionPane.YES_OPTION) {
            getToolkit().beep();
            this.setVisible(false);
            Inicio.jPanel1.removeAll();
        }
    }//GEN-LAST:event_BotonSalirMouseClicked
    
    
    private void BotonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarMouseClicked
        if (jtctplaca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Placa Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtpropietario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Propietario Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtmarca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Marca Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtModelo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Modelo Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtareadescripcion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Descripcion Vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (jcombotipovehiculo.getSelectedIndex() == 0) {
                carro = new Carro(jtctplaca.getText().trim(),
                        jtxtpropietario.getText().trim(), jtxtmarca.getText().trim());
                carro.setDrescripcion(jtxtareadescripcion.getText().toUpperCase());
                carro.setModelo(jtxtModelo.getText().trim());
                JOptionPane.showMessageDialog(null, "Datos Ingresados: " + carro.getPlaca().trim(), "Agregado ", JOptionPane.INFORMATION_MESSAGE);
                Limpiar();
                Insertar(carro, null);

            } else {
                Moto moto = new Moto(jtctplaca.getText().trim(), jtxtpropietario.getText().trim(), jtxtmarca.getText().trim());
                moto.setDrescripcion(jtxtareadescripcion.getText().toUpperCase());
                JOptionPane.showMessageDialog(null, "Datos Ingresados: " + moto.getPlaca().trim(), "Agregado ", JOptionPane.INFORMATION_MESSAGE);
                moto.setModelo(jtxtModelo.getText().trim());
                moto.setDrescripcion(jtxtareadescripcion.getText().toUpperCase());
                Limpiar();
                Insertar(null, moto);
            }
        }
        
    }//GEN-LAST:event_BotonAgregarMouseClicked

    private void BotonSalirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotonSalirKeyTyped
        
    }//GEN-LAST:event_BotonSalirKeyTyped

    private void BotonSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotonSalirKeyPressed
        
    }//GEN-LAST:event_BotonSalirKeyPressed

    private void BotonSalirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotonSalirKeyReleased
        
    }//GEN-LAST:event_BotonSalirKeyReleased

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        
    }//GEN-LAST:event_formKeyTyped

    private void jtxtBuscarvehiculoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarvehiculoKeyTyped
        if(jtxtBuscarvehiculo.getText().length() > (8 -1)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error",JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if((caracteres < 65 || caracteres > 90) && (caracteres < 97 || caracteres >122 ) && (caracteres <48 || caracteres >57) 
                && (caracteres != 8) && (caracteres != 10 ) ){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }else   
            Buscar();
    }//GEN-LAST:event_jtxtBuscarvehiculoKeyTyped

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Limpiar();
        int size = jTable1.getRowCount();
        DefaultTableModel Tabla = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < size; i++) {
            Tabla.removeRow(0);
        }
        jTable1.updateUI();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jtctplacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtctplacaKeyTyped
        if(jtctplaca.getText().length() > (8 -1)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error",JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if((caracteres < 65 || caracteres > 90) && (caracteres < 97 || caracteres >122 ) && (caracteres <48 || caracteres >57) 
                && (caracteres != 8) && (caracteres != 10 ) ){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtctplacaKeyTyped

    private void jtxtpropietarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpropietarioKeyTyped
        if(jtxtBuscarvehiculo.getText().length() > (40 -1)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error",JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if((caracteres < 65 || caracteres > 90) && (caracteres < 97 || caracteres >122 ) && (caracteres != 8) && (caracteres != 10 ) ){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtpropietarioKeyTyped

    private void jtxtBuscarvehiculoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarvehiculoKeyPressed
       if (evt.isControlDown() || evt.isShiftDown() || evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtBuscarvehiculoKeyPressed

    private void jtctplacaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtctplacaKeyPressed
        if (evt.isControlDown() || evt.isShiftDown() || evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtctplacaKeyPressed

    private void jtxtpropietarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpropietarioKeyPressed
        if (evt.isControlDown() || evt.isShiftDown() || evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtpropietarioKeyPressed

    private void jtxtmarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtmarcaKeyPressed
        if (evt.isControlDown() || evt.isShiftDown() || evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtmarcaKeyPressed

    private void jtxtmarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtmarcaKeyTyped
        if(jtctplaca.getText().length() > (100 -1)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error",JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if((caracteres < 65 || caracteres > 90) && (caracteres < 97 || caracteres >122 ) && (caracteres != 8) && (caracteres != 10 ) ){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtmarcaKeyTyped

    private void jtxtModeloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtModeloKeyPressed
        if (evt.isControlDown() || evt.isShiftDown() || evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jtxtModeloKeyPressed

    private void jtxtModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtModeloKeyTyped
        if(jtctplaca.getText().length() > (25 -1)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error",JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if((caracteres < 65 || caracteres > 90) && (caracteres < 97 || caracteres >122 ) && (caracteres <48 || caracteres >57) 
                && (caracteres != 8) && (caracteres != 10 ) ){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtxtModeloKeyTyped

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if (jtxtBuscarvehiculo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese datos para Buscar ", "Error", JOptionPane.INFORMATION_MESSAGE);
        }else{
            search();
        }
    }//GEN-LAST:event_jButton2MouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    public static javax.swing.JComboBox jcombotipovehiculo;
    private javax.swing.JLabel jlabelfecha;
    private javax.swing.JTextField jtctplaca;
    private javax.swing.JTextField jtxtBuscarvehiculo;
    private javax.swing.JTextField jtxtModelo;
    private javax.swing.JTextArea jtxtareadescripcion;
    private javax.swing.JTextField jtxtmarca;
    private javax.swing.JTextField jtxtpropietario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Insertar(Carro car, Moto mot) {
        try {
            Connection con = ConectarBD.ConexcionBD.Conectar();
            String SQL = "INSERT INTO  Vehiculo (placa,modelo,propietario,tipo_vehiculo,hora_entrada,descripcion,fecha_entrada,marca) VALUES (?,?,?,?,?,?,?,?)";
            PreparedStatement preparar = con.prepareStatement(SQL);
            if (jcombotipovehiculo.getSelectedIndex() == 0) {
                preparar.setString(1, car.getPlaca());
                preparar.setString(2, car.getModelo());
                preparar.setString(3, car.getPropietarioVehiculo());
                preparar.setString(4, jcombotipovehiculo.getSelectedItem().toString().toUpperCase());
                preparar.setString(5, car.getHora());
                preparar.setString(6, car.getDrescripcion());
                preparar.setString(7, car.getFechaEntrada());
                preparar.setString(8, car.getMarca());
                preparar.executeUpdate();
            }else{
                preparar.setString(1, mot.getPlaca());
                preparar.setString(2, mot.getModelo());
                preparar.setString(3, mot.getPropietarioVehiculo());
                preparar.setString(4, jcombotipovehiculo.getSelectedItem().toString().toUpperCase());
                preparar.setString(5, mot.getHora());
                preparar.setString(6, mot.getDrescripcion());
                preparar.setString(7, mot.getFechaEntrada());
                preparar.setString(8, mot.getMarca());
                preparar.executeUpdate();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex , "Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void Remover() {
        
    }
    
    public void search(){
        try {
            Connection con = ConectarBD.ConexcionBD.Conectar();
            String Sql = "SELECT * FROM Vehiculo WHERE placa like \'%"+jtxtBuscarvehiculo.getText().trim()+"%\'";
            PreparedStatement preparar = con.prepareStatement(Sql);
            ResultSet Resultado = preparar.executeQuery();
            DefaultTableModel Tabla = (DefaultTableModel) jTable1.getModel();
            Tabla.getDataVector().clear();
            while (Resultado.next()) {
                Object[] Datos = new Object[7];
                Datos[0] = Resultado.getString("id_vehiculo");
                Datos[1] = Resultado.getString("placa");
                Datos[2] = Resultado.getString("modelo");
                Datos[3] = Resultado.getString("propietario");
                Datos[4] = Resultado.getString("tipo_vehiculo");
                Datos[6] = Resultado.getString("hora_entrada");
                Datos[5] = Resultado.getString("descripcion");
                Tabla.addRow(Datos);
            }
            jTable1.setModel(Tabla);
        } catch (ClassNotFoundException | SQLException e) {
        }
        
    }

    @Override
    public void listar() {
        try {
            Connection con = ConectarBD.ConexcionBD.Conectar();
            String Sql = "SELECT * FROM Vehiculo";
            PreparedStatement preparar = con.prepareStatement(Sql);
            ResultSet Resultado = preparar.executeQuery();
            DefaultTableModel Tabla = (DefaultTableModel) jTable1.getModel();
            Tabla.getDataVector().clear();
            while (Resultado.next()) {
                Object[] Datos = new Object[7];
                Datos[0] = Resultado.getString("id_vehiculo");
                Datos[1] = Resultado.getString("placa");
                Datos[2] = Resultado.getString("modelo");
                Datos[3] = Resultado.getString("propietario");
                Datos[4] = Resultado.getString("tipo_vehiculo");
                Datos[6] = Resultado.getString("hora_entrada");
                Datos[5] = Resultado.getString("descripcion");
                Tabla.addRow(Datos);
            }
            jTable1.setModel(Tabla);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex , "Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }

    @Override
    public void Buscar() {
        try {
            DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
            Connection con = ConectarBD.ConexcionBD.Conectar();
            String SQL = "SELECT * FROM Vehiculo WHERE placa like \'%"+jtxtBuscarvehiculo.getText().trim()+"%\'";
            PreparedStatement preparar = con.prepareStatement(SQL);
            ResultSet resultado = preparar.executeQuery();
            tabla.getDataVector().clear();
            jtxtareadescripcion.setText("");
            if (jtxtBuscarvehiculo.getText().equals("")) {
                tabla.getDataVector().clear();
                jtxtareadescripcion.setText("");
                jtxtareadescripcion.setEditable(true);
                jTable1.updateUI();
            }else{
                while (resultado.next()) {
                Object[] Datos = new Object[7];
                Datos[0] = resultado.getString("id_vehiculo");
                Datos[1] = resultado.getString("placa");
                Datos[2] = resultado.getString("modelo");
                Datos[3] = resultado.getString("propietario");
                Datos[4] = resultado.getString("tipo_vehiculo");
                Datos[6] = resultado.getString("hora_entrada");
                jtxtareadescripcion.setText(resultado.getString("descripcion"));
                jtxtareadescripcion.setEditable(false);
                Datos[5] = resultado.getString("fecha_entrada");
                tabla.addRow(Datos);
                jTable1.updateUI();
            }
            jTable1.setModel(tabla);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex , "Error",JOptionPane.ERROR_MESSAGE);
        }
    }
}
