
package Panel_Ingresar_y_Salir_Vehiculo;

import Clases.Carro;
import Clases.Moto;
import Ejecucion.Inicio;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tabla.ModeloTabla;

/**
 *
 * @author TaGCode
 */
public class Salir_Vehiculo extends javax.swing.JPanel implements ConectarBD.Metodos{

    /**
     * Creates new form Ingresar_Usuario
     */
    ModeloTabla Color = new ModeloTabla();
    public Salir_Vehiculo() {
        System.gc();
        initComponents();
        jTable1.setDefaultRenderer(Object.class, Color);
        Font tamanio = new Font("Dialog",Font.BOLD,14);
        jTable1.getTableHeader().setFont(tamanio);
        
    }

    void limpiar (){
        jtxtBuscarvehiculo.setText("");
        JTXTAREADESCRIPCION.setText("");
        DefaultTableModel Table = (DefaultTableModel) jTable1.getModel();
        int size = jTable1.getRowCount();
        for (int i = 0; i < size; i++) {
            Table.removeRow(0);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtBuscarvehiculo = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTXTAREADESCRIPCION = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALIDA VEHICULO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 36))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel1.setText("Vehiculo:");

        jtxtBuscarvehiculo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtxtBuscarvehiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBuscarvehiculoKeyTyped(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Buscar.png"))); // NOI18N
        jButton3.setText("Buscar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtBuscarvehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jButton3))
                    .addComponent(jtxtBuscarvehiculo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sign-delete-icon_34364.png"))); // NOI18N
        jButton1.setText("Eliminar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/checklist_25365.png"))); // NOI18N
        jButton2.setText("Listar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/action_exit_close_remove_13915.png"))); // NOI18N
        jButton4.setText("Salir");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JTXTAREADESCRIPCION.setEditable(false);
        JTXTAREADESCRIPCION.setColumns(20);
        JTXTAREADESCRIPCION.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        JTXTAREADESCRIPCION.setLineWrap(true);
        JTXTAREADESCRIPCION.setRows(5);
        JTXTAREADESCRIPCION.setWrapStyleWord(true);
        jScrollPane1.setViewportView(JTXTAREADESCRIPCION);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Descripcion:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex , int colIndex){
                return false;
            }
        };
        jTable1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PLACA", "MODELO", "PROPIETARIO", "TIPO VEHICULO", "HORA ENTRADA", "FECHA ENTRADA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jTable1.setFocusable(false);

        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        int aux = JOptionPane.showConfirmDialog(null, "Esta Seguro Salir", "Salir", JOptionPane.ERROR_MESSAGE);
        if (aux == JOptionPane.YES_OPTION) {
            getToolkit().beep();
            this.setVisible(false);
            Inicio.jPanel1.removeAll();
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jtxtBuscarvehiculoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarvehiculoKeyTyped
        if (jtxtBuscarvehiculo.getText().length() > (8 - 1)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite", "Error", JOptionPane.ERROR_MESSAGE);
        }
        char caracteres = evt.getKeyChar();
        if ((caracteres < 65 || caracteres > 90) && (caracteres < 97 || caracteres > 122) && (caracteres < 48 || caracteres > 57)
                && (caracteres != 8) && (caracteres != 10)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Caracter Denegado ", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Buscar();
        }
    }//GEN-LAST:event_jtxtBuscarvehiculoKeyTyped

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if (jtxtBuscarvehiculo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese datos para Buscar ", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Buscar();
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (jtxtBuscarvehiculo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese Numero de Placa Para Eliminar", "Error", JOptionPane.ERROR_MESSAGE);
        }else {
            Remover();
        }
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        listar();
    }//GEN-LAST:event_jButton2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTXTAREADESCRIPCION;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxtBuscarvehiculo;
    // End of variables declaration//GEN-END:variables

    
    
    @Override
    public void Insertar(Carro car, Moto mot) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void Remover() {
        try {
            Connection con = ConectarBD.ConexcionBD.Conectar();
            String Sql = "DELETE  FROM Vehiculo WHERE placa =\'"+jtxtBuscarvehiculo.getText().trim()+"\'";
            PreparedStatement preparar = con.prepareStatement(Sql);
            preparar.executeUpdate();
            limpiar();
            JOptionPane.showMessageDialog(null, "Eliminado");
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex , "Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void listar() {
        try {
            Connection con = ConectarBD.ConexcionBD.Conectar();
            String Sql = "SELECT * FROM Vehiculo";
            PreparedStatement preparar = con.prepareStatement(Sql);
            ResultSet Resultado = preparar.executeQuery();
            DefaultTableModel Tabla = (DefaultTableModel) jTable1.getModel();
            Tabla.getDataVector().clear();
            while (Resultado.next()) {
                Object[] Datos = new Object[7];
                Datos[0] = Resultado.getString("id_vehiculo");
                Datos[1] = Resultado.getString("placa");
                Datos[2] = Resultado.getString("modelo");
                Datos[3] = Resultado.getString("propietario");
                Datos[4] = Resultado.getString("tipo_vehiculo");
                Datos[6] = Resultado.getString("hora_entrada");
                Datos[5] = Resultado.getString("descripcion");
                Tabla.addRow(Datos);
            }
            jTable1.setModel(Tabla);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex , "Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void Buscar() {
        try {
            Connection con = ConectarBD.ConexcionBD.Conectar();
            String SQL = "SELECT * FROM Vehiculo WHERE placa = \'"+jtxtBuscarvehiculo.getText().trim()+"\'";
            PreparedStatement preparar = con.prepareStatement(SQL);
            ResultSet resultado = preparar.executeQuery();
            DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
            tabla.getDataVector().clear();
            while (resultado.next()) {
                Object[] Datos = new Object[7];
                Datos[0] = resultado.getString("id_vehiculo");
                Datos[1] = resultado.getString("placa");
                Datos[2] = resultado.getString("modelo");
                Datos[3] = resultado.getString("propietario");
                Datos[4] = resultado.getString("tipo_vehiculo");
                Datos[5] = resultado.getString("hora_entrada");
                JTXTAREADESCRIPCION.setText(resultado.getString("descripcion"));
                Datos[6] = resultado.getString("fecha_entrada");
                tabla.addRow(Datos);
            }
            jTable1.setModel(tabla);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex , "Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
}
